import = ["/home/inferno/.config/alacritty/themes/nord.yaml"]

[cursor.style]
blinking = "Off"
shape = "Underline"

[font]
size = 18.00

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9

[window.dimensions]
columns = 101
lines = 22

[window.padding]
x = 5
y = 5
